LibraryManagementSystem.Web/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagementSystem.Web.Areas.Admin.Controllers
{
    public class HomeController : BaseAdminController
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

LibraryManagementSystem.Web/Areas/Admin/Controllers/SystemMetricsController.cs
using LibraryManagementSystem.Web.Areas.Admin.Services.Interfaces;
using LibraryManagementSystem.Web.Areas.Admin.ViewModels.SystemMetrtics;
using Microsoft.AspNetCore.Mvc;

namespace LibraryManagementSystem.Web.Areas.Admin.Controllers
{
    public class SystemMetricsController : BaseAdminController
    {
        private readonly ISystemMetricsService systemMetricsService;

        public SystemMetricsController(ISystemMetricsService systemMetricsService)
        {
            this.systemMetricsService = systemMetricsService;
        }

        [HttpGet]
        public async Task<IActionResult> Metrics()
        {
            SystemMetricsViewModel model = await this.systemMetricsService.GetSystemMetricsAsync();

            return this.View(model);
        }
    }
}

LibraryManagementSystem.Web/Controllers/EditionController.cs
using LibraryManagementSystem.Services.Data.Interfaces;
using LibraryManagementSystem.Web.ViewModels.Edition;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static LibraryManagementSystem.Common.NotificationMessageConstants;
using static LibraryManagementSystem.Common.UserRoleNames;

namespace LibraryManagementSystem.Web.Controllers
{
    public class EditionController : BaseController
    {
        private readonly IEditionService editionService;
        private readonly IBookService bookService;

        public EditionController(IEditionService editionService, IBookService bookService)
        {
            this.editionService = editionService;
            this.bookService = bookService;
        }

        [HttpGet]
        [Authorize(Roles = AdminRole)]
        public async Task<IActionResult> Add()
        {
            try
            {
                EditionFormModel model = await this.editionService.GetCreateNewEditionModelAsync();

                return this.View(model);
            }
            catch
            {
                return this.GeneralError();
            }
        }

        [HttpPost]
        [Authorize(Roles = AdminRole)]
        public async Task<IActionResult> Add(EditionFormModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            try
            {
                bool bookExists = await this.bookService.BookExistByIdAsync(model.BookId);

                if (!bookExists)
                {
                    this.TempData[ErrorMessage] = "Such Book does not exists!";

                    return this.RedirectToAction("All", "Book");
                }

                bool editionExists = await this.editionService.EditionExistByVersionPublisherAndBookIdAsync(model.Version, model.Publisher, model.BookId);

                if (editionExists)
                {
                    this.TempData[ErrorMessage] = "Edition with the same Book, Version and Publisher already exists!";

                    return this.RedirectToAction("Details", "Book", new { id = model.BookId });
                }

                await this.editionService.AddEditionAsync(model);

                this.TempData[SuccessMessage] = $"Successfully added Edition to the Book.";
            }
            catch
            {
                this.TempData[ErrorMessage] = "There was problem with adding the Edition to the Book!";
            }

            return this.RedirectToAction("Details", "Book", new { id = model.BookId });
        }

        [HttpGet]
        [Authorize(Roles = AdminRole)]
        public async Task<IActionResult> Edit(string id)
        {
            try
            {
                bool editionExists = await this.editionService.EditionExistByIdAsync(id);

                if (!editionExists)
                {
                    this.TempData[ErrorMessage] = "Such Book-Edition does not exists!";

                    return this.RedirectToAction("All", "Book");
                }

                var edition = await this.editionService.GetEditionForEditByIdAsync(id);

                return this.View(edition);
            }
            catch
            {
                return this.GeneralError();
            }
        }

        [HttpPost]
        [Authorize(Roles = AdminRole)]
        public async Task<IActionResult> Edit(string id, EditionFormModel model)
        {
            var bookId = await this.editionService.GetBookIdByEditionIdAsync(id);

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            try
            {
                bool bookExists = await this.bookService.BookExistByIdAsync(model.BookId);

                if (!bookExists)
                {
                    this.TempData[ErrorMessage] = "Such Book does not exists!";

                    return this.RedirectToAction("All", "Book");
                }

                var editionExists = await this.editionService.EditionExistByIdAsync(id);

                if (!editionExists)
                {
                    this.TempData[ErrorMessage] = "Such Book-Edition does not exists!";

                    return this.RedirectToAction("All", "Book");
                }

                await this.editionService.EditBookEditionAsync(id, model);

                this.TempData[SuccessMessage] = "Succesfully edited Book-Edition.";
            }
            catch
            {
                this.TempData[ErrorMessage] = "There was problem with editing the Book-Edition!";
            }

            return this.RedirectToAction("Details", "Book", new { id = bookId });
        }

        [HttpGet]
        [Authorize(Roles = AdminRole)]
        public async Task<IActionResult> Delete(string id)
        {
            var bookId = await this.editionService.GetBookIdByEditionIdAsync(id);

            var editionExists = await this.editionService.EditionExistByIdAsync(id);

            if (!editionExists)
            {
                this.TempData[ErrorMessage] = "Such Book-Edition does not exists!";

                return this.RedirectToAction("All", "Book");
            }

            try
            {
                await this.editionService.DeleteEditionAsync(id);

                this.TempData[SuccessMessage] = "Succesfully deleted Book-Edition.";
            }
            catch
            {
                this.TempData[ErrorMessage] = "There was problem with deleting the Book-Edition!";
            }

            return this.RedirectToAction("Details", "Book", new { id = bookId });
        }

        private IActionResult GeneralError()
        {
            TempData[ErrorMessage] = "Unexpected error occurred! Please try again later or contact administrator";

            return this.RedirectToAction("Index", "Home");
        }
    }
}

LibraryManagementSystem.Web/Controllers/HomeController.cs
using LibraryManagementSystem.Services.Data.Interfaces;
using LibraryManagementSystem.Web.ViewModels.Home;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static LibraryManagementSystem.Common.GeneralApplicationConstants;
using static LibraryManagementSystem.Common.UserRoleNames;

namespace LibraryManagementSystem.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly IBookService bookService;

        public HomeController(IBookService bookService)
        {
            this.bookService = bookService;
        }

        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            if (this.User.IsInRole(AdminRole))
            {
                return this.RedirectToAction("Index", "Home", new { Area = AdminAreaName});
            }

            IEnumerable<IndexViewModel> viewModel = await this.bookService.LastNineBooksAsync();

            return this.View(viewModel);
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(int statusCode)
        {
            if (statusCode == 400 || statusCode == 404)
            {
                return this.View("Error404");
            }
            else if (statusCode == 401)
            {
                return this.View("Error401");
            }
            else if (statusCode == 403)
            {
                return this.View("Error403");
            }
            else if (statusCode == 500)
            {
                return this.View("Error500");
            }

            return this.View();
        }
    }
}

LibraryManagementSystem.Web/Controllers/UserController.cs
using Griesoft.AspNetCore.ReCaptcha;
using LibraryManagementSystem.Data.Models;
using LibraryManagementSystem.Services.Data.Interfaces;
using LibraryManagementSystem.Web.ViewModels.User;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Caching.Memory;
using static LibraryManagementSystem.Common.GeneralApplicationConstants;
using static LibraryManagementSystem.Common.NotificationMessageConstants;
using static LibraryManagementSystem.Common.UserRoleNames;

namespace LibraryManagementSystem.Web.Controllers
{
    public class UserController : Controller
    {
        private readonly SignInManager<ApplicationUser> signInManager;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IUserService userService;
        private readonly IMemoryCache memoryCache;

        public UserController(SignInManager<ApplicationUser> signInManager,
                                UserManager<ApplicationUser> userManager,
                                IUserService userService, 
                                IMemoryCache memoryCache)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
            this.userService = userService;
            this.memoryCache = memoryCache;
        }

        [HttpGet]
        public IActionResult Register()
        {
            return this.View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [ValidateRecaptcha(Action = nameof(Register), ValidationFailedAction = ValidationFailedAction.ContinueRequest)]
        public async Task<IActionResult> Register(RegisterFormModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View();
            }

            ApplicationUser user = new ApplicationUser()
            {
                FirstName = model.FirstName,
                LastName = model.LastName,
                UserName = model.Username,
                Email = model.Email,
                PhoneNumber = model.PhoneNumber,
                Address = model.Address,
                Country = model.Country,
                City = model.City,
                DateOfBirth = model.DateOfBirth,
                MaxLoanedBooks = MaxNumberOfBooksAllowed,
                SecurityStamp = Guid.NewGuid().ToString(),
            };

            await this.userManager.SetEmailAsync(user, model.Email);
            await this.userManager.SetUserNameAsync(user, model.Username);

            IdentityResult result = await this.userManager.CreateAsync(user, model.Password);

            if (!result.Succeeded)
            {
                foreach (IdentityError error in result.Errors)
                {
                    this.ModelState.AddModelError(string.Empty, error.Description);
                }

                return this.View(model);
            }

            await this.userManager.AddToRoleAsync(user, UserRole);
            await this.signInManager.SignInAsync(user, isPersistent: false);

            this.memoryCache.Remove(UsersCacheKey);

            this.TempData[SuccessMessage] = "You have registered successfully.";

            return this.RedirectToAction("Index", "Home");
        }

        [HttpGet]
        public async Task<IActionResult> Login()
        {
            await this.HttpContext.SignOutAsync(IdentityConstants.ExternalScheme);

            LoginFormModel model = new LoginFormModel();

            return this.View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginFormModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }
            var user = await this.userManager.FindByNameAsync(model.Username);

            if (user != null)
            {
                bool isDeleted = await this.userService.IsUserDeletedAsync(user!.Id.ToString());
                if (isDeleted)
                {
                    this.TempData[ErrorMessage] = "The account you are trying to login is deleted!";

                    return this.RedirectToAction("Index", "Home");
                }
            }

            var result = await this.signInManager.PasswordSignInAsync(model.Username, model.Password, model.RememberMe, false);

            if (!result.Succeeded)
            {
                this.TempData[ErrorMessage] = "Your Username and/or Password is incorrect!";
                return this.View(model);
            }

            this.TempData[SuccessMessage] = "You have logged in successfully.";
            
            if (user != null)
            {
                // Update Security Stamp upon successful login
                await this.userManager.UpdateSecurityStampAsync(user);
            }
            else
            {
                this.TempData[ErrorMessage] = "There was an error while logging you in!";
            }

            return this.RedirectToAction("Index", "Home");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Logout()
        {
            await this.signInManager.SignOutAsync();

            // Update Security Stamp upon logout to invalidate any existing tokens
            var user = await this.userManager.GetUserAsync(User);
            if (user != null)
            {
                await this.userManager.UpdateSecurityStampAsync(user);
            }
            else
            {
                this.TempData[ErrorMessage] = "There was a problem with the Update Security Stamp!";
            }

            return this.RedirectToAction("Index", "Home");
        }
    }
}

LibraryManagementSystem.Web/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="mt-4 p-5 text-center" style="background-color: #fdf6e3;">
    <h2 class="display-4">Hello, dear Admin!</h2>
    <p class="lead mb-1 mt-3">
        This is your administrator area - you can <b>read</b>, <b>create</b>,
        <b>delete</b> and <b>edit</b> <u>Categories,</u> <u>Authors,</u> <u>Books,</u> and <u>Editions</u>.
    </p>
    <hr class="my-4">
    <br />
    <div class="container">
        <div class="row">
            <div class="col-md-6 mb-3 d-flex align-items-center justify-content-between">
                <div>
                    <a asp-area="" asp-controller="Book" asp-action="All" class="btn btn-primary btn-lg">All Books</a>
                    <span class="text-on-left" style="margin-left: 10px;">
                        View, navigate and search all <strong>books</strong> added into the system. <strong>Edit</strong> and <strong>Attach</strong> files to Books and Editions.
                    </span>
                </div>
            </div>
            <div class="col-md-6 mb-3 d-flex align-items-center justify-content-between">
                <div>
                    <span class="text-on-right" style="margin-left: 50px;">
                        <strong>Add</strong> new <strong>books</strong> into the system.
                    </span>
                </div>
                <div>
                    <a asp-area="" asp-controller="Book" asp-action="Add" class="btn btn-success btn-lg">Add Book</a>
                </div>
            </div>
        </div>
        <br />
        <br />
        <div class="row">
            <div class="col-md-6 mb-3 d-flex align-items-center justify-content-between">
                <div>
                    <a asp-area="" asp-controller="Author" asp-action="All" class="btn btn-primary btn-lg">All Authors</a>
                    <span class="text-on-left" style="margin-left: 10px;">
                        View, navigate and search all <strong>authors</strong> added into the system. Take a look at their Details.
                    </span>
                </div>
            </div>
            <div class="col-md-6 mb-3 d-flex align-items-center justify-content-between">
                <div>
                    <span class="text-on-right" style="margin-left: 50px;">
                        <strong>Add</strong> new <strong>author</strong> into the system.
                    </span>
                </div>
                <div>
                    <a asp-area="" asp-controller="Author" asp-action="Add" class="btn btn-success btn-lg">Add Author</a>
                </div>
            </div>
        </div>
        <br />
        <br />
        <div class="row">
            <div class="col-md-6 mb-3 d-flex align-items-center justify-content-between">
                <div>
                    <a asp-area="" asp-controller="Category" asp-action="All" class="btn btn-primary btn-lg">All Categories</a>
                    <span class="text-on-left" style="margin-left: 10px;">
                        View all <strong>categories</strong> added into the system.
                    </span>
                </div>
            </div>
            <div class="col-md-6 mb-3 d-flex align-items-center justify-content-between">
                <div>
                    <span class="text-on-right" style="margin-left: 50px;">
                        <strong>Add</strong> new <strong>category</strong> into the system.
                    </span>
                </div>
                <div>
                    <a asp-area="" asp-controller="Category" asp-action="Add" class="btn btn-success btn-lg">Add Category</a>
                </div>
            </div>
        </div>
        <br />
        <br />
        <div class="row">
            <div class="col-md-6 mb-3 d-flex align-items-center justify-content-between"></div>
            <div class="col-md-6 mb-3 d-flex align-items-center justify-content-between">
                <div>
                    <span class="text-on-right" style="margin-left: 50px;">
                        <strong>Add</strong> new <strong>edition</strong> to existing book into the system.
                    </span>
                </div>
                <div>
                    <a asp-area="" asp-controller="Edition" asp-action="Add" class="btn btn-success btn-lg">Add Edition</a>
                </div>
            </div>
        </div>
    </div>
    <hr class="my-4">
    <p class="lead mb-1 mt-3">
        From this part you can also see <b>all users in the system, promote and demote them</b> and have some <b>metrics</b> about the system for knowledge.
    </p>
    <hr />
    <br></br>
    <div class="row">
        <div class="col-md-6 mb-3 d-flex align-items-center justify-content-between">
            <div>
                <a asp-area="Admin" asp-controller="User" asp-action="All" class="btn btn-info btn-lg">Users</a>
                <span class="text-on-left" style="margin-left: 10px;">
                    View all <strong>registered users, promote and demote them.</strong>
                </span>
            </div>
        </div>
        <div class="col-md-6 mb-3 d-flex align-items-center justify-content-between">
            <div>
                <span class="text-on-right" style="margin-left: 50px;">
                    <strong>Get information</strong> about different <strong>metrics</strong> from the system.
                </span>
            </div>
            <div>
                <a asp-area="Admin" asp-controller="SystemMetrics" asp-action="Metrics" class="btn btn-info btn-lg">Statistics</a>
            </div>
        </div>
    </div>
</div>