LibraryManagementSystem.Web/Controllers/EditionController.cs
using LibraryManagementSystem.Services.Data.Interfaces;
using LibraryManagementSystem.Web.ViewModels.Edition;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static LibraryManagementSystem.Common.NotificationMessageConstants;
using static LibraryManagementSystem.Common.UserRoleNames;

namespace LibraryManagementSystem.Web.Controllers
{
    public class EditionController : BaseController
    {
        private readonly IEditionService editionService;
        private readonly IBookService bookService;

        public EditionController(IEditionService editionService, IBookService bookService)
        {
            this.editionService = editionService;
            this.bookService = bookService;
        }

        [HttpGet]
        [Authorize(Roles = AdminRole)]
        public async Task<IActionResult> Add()
        {
            try
            {
                EditionFormModel model = await this.editionService.GetCreateNewEditionModelAsync();

                return this.View(model);
            }
            catch
            {
                return this.GeneralError();
            }
        }

        [HttpPost]
        [Authorize(Roles = AdminRole)]
        public async Task<IActionResult> Add(EditionFormModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            try
            {
                bool bookExists = await this.bookService.BookExistByIdAsync(model.BookId);

                if (!bookExists)
                {
                    this.TempData[ErrorMessage] = "Such Book does not exists!";

                    return this.RedirectToAction("All", "Book");
                }

                bool editionExists = await this.editionService.EditionExistByVersionPublisherAndBookIdAsync(model.Version, model.Publisher, model.BookId);

                if (editionExists)
                {
                    this.TempData[ErrorMessage] = "Edition with the same Book, Version and Publisher already exists!";

                    return this.RedirectToAction("Details", "Book", new { id = model.BookId });
                }

                await this.editionService.AddEditionAsync(model);

                this.TempData[SuccessMessage] = $"Successfully added Edition to the Book.";
            }
            catch
            {
                this.TempData[ErrorMessage] = "There was problem with adding the Edition to the Book!";
            }

            return this.RedirectToAction("Details", "Book", new { id = model.BookId });
        }

        [HttpGet]
        [Authorize(Roles = AdminRole)]
        public async Task<IActionResult> Edit(string id)
        {
            try
            {
                bool editionExists = await this.editionService.EditionExistByIdAsync(id);

                if (!editionExists)
                {
                    this.TempData[ErrorMessage] = "Such Book-Edition does not exists!";

                    return this.RedirectToAction("All", "Book");
                }

                var edition = await this.editionService.GetEditionForEditByIdAsync(id);

                return this.View(edition);
            }
            catch
            {
                return this.GeneralError();
            }
        }

        [HttpPost]
        [Authorize(Roles = AdminRole)]
        public async Task<IActionResult> Edit(string id, EditionFormModel model)
        {
            var bookId = await this.editionService.GetBookIdByEditionIdAsync(id);

            if (!this.ModelState.IsValid)
            {
                return this.View(model);
            }

            try
            {
                bool bookExists = await this.bookService.BookExistByIdAsync(model.BookId);

                if (!bookExists)
                {
                    this.TempData[ErrorMessage] = "Such Book does not exists!";

                    return this.RedirectToAction("All", "Book");
                }

                var editionExists = await this.editionService.EditionExistByIdAsync(id);

                if (!editionExists)
                {
                    this.TempData[ErrorMessage] = "Such Book-Edition does not exists!";

                    return this.RedirectToAction("All", "Book");
                }

                await this.editionService.EditBookEditionAsync(id, model);

                this.TempData[SuccessMessage] = "Succesfully edited Book-Edition.";
            }
            catch
            {
                this.TempData[ErrorMessage] = "There was problem with editing the Book-Edition!";
            }

            return this.RedirectToAction("Details", "Book", new { id = bookId });
        }

        [HttpGet]
        [Authorize(Roles = AdminRole)]
        public async Task<IActionResult> Delete(string id)
        {
            var bookId = await this.editionService.GetBookIdByEditionIdAsync(id);

            var editionExists = await this.editionService.EditionExistByIdAsync(id);

            if (!editionExists)
            {
                this.TempData[ErrorMessage] = "Such Book-Edition does not exists!";

                return this.RedirectToAction("All", "Book");
            }

            try
            {
                await this.editionService.DeleteEditionAsync(id);

                this.TempData[SuccessMessage] = "Succesfully deleted Book-Edition.";
            }
            catch
            {
                this.TempData[ErrorMessage] = "There was problem with deleting the Book-Edition!";
            }

            return this.RedirectToAction("Details", "Book", new { id = bookId });
        }

        private IActionResult GeneralError()
        {
            TempData[ErrorMessage] = "Unexpected error occurred! Please try again later or contact administrator";

            return this.RedirectToAction("Index", "Home");
        }
    }
}

LibraryManagementSystem.Web/Controllers/FileController.cs
using LibraryManagementSystem.Data.Models;
using LibraryManagementSystem.Services.Data.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using static LibraryManagementSystem.Common.NotificationMessageConstants;
using static LibraryManagementSystem.Common.UserRoleNames;

namespace LibraryManagementSystem.Web.Controllers
{
    public class FileController : BaseController
    {
        private readonly IFileService fileService;

        public FileController(IFileService fileService)
        {
            this.fileService = fileService;
        }

        [HttpPost]
        [Authorize(Roles = AdminRole)]
        public async Task<IActionResult> UploadFile(string id, IFormFile file, string entityType)
        {
            try
            {
                // Check file Length
                if (file == null || file.Length == 0)
                {
                    this.TempData[ErrorMessage] = "No file is chosen for upload!";

                    if (entityType == "Edition")
                    {
                        return this.RedirectToAction("Edit", "Edition", new { id });

                    }

                    return this.RedirectToAction("Edit", "Book", new { id });
                }

                // Check File extension
                if (!file.FileName.EndsWith(".txt"))
                {
                    this.TempData[ErrorMessage] = "Only .txt files are allowed!";

                    return this.RedirectToAction("Edit", "Book", new { id });
                }

                // Check if entityType is valid
                if (entityType != nameof(Book) && entityType != nameof(Edition))
                {
                    this.TempData[ErrorMessage] = "Invalid entity type!";

                    return this.RedirectToAction("Edit", "Book", new { id });
                }

                string filePath = await this.fileService.UploadFileAsync(id, file, entityType);

                this.TempData[SuccessMessage] = $"Successfully uploaded {entityType} file.";

                return this.RedirectToAction("All", "Book");
            }
            catch
            {
                this.TempData[ErrorMessage] = "There was problem with uploding the file!";
            }

            return this.RedirectToAction("All", "Book");
        }

        [HttpPost]
        [Authorize(Roles = AdminRole)]
        public async Task<IActionResult> UploadImageFile(string id, IFormFile file, string entityType)
        {
            try
            {
                // Check file Length
                if (file == null || file.Length == 0)
                {
                    this.TempData[ErrorMessage] = "No file is chosen for upload!";

                    if (entityType == nameof(Book))
                    {
                        return this.RedirectToAction("Edit", "Book", new { id });
                    }

                    return this.RedirectToAction("Edit", "Author", new { id });
                }

                // Check File extension
                if (!file.FileName.EndsWith(".txt") && !file.FileName.EndsWith(".jpg"))
                {
                    this.TempData[ErrorMessage] = "Only .txt or .jpg files are allowed!";

                    if (entityType == nameof(Book))
                    {
                        return this.RedirectToAction("Edit", "Book", new { id });
                    }

                    return this.RedirectToAction("Edit", "Author", new { id });
                }

                // Check if entityType is valid
                if (entityType != nameof(Book) && entityType != nameof(Author))
                {
                    this.TempData[ErrorMessage] = "Invalid entity type!";

                    return this.RedirectToAction("Index", "Home", new { id });
                }

                string filePath = await this.fileService.UploadImageFileAsync(id, file, entityType);

                this.TempData[SuccessMessage] = $"Successfully uploaded {entityType} image file.";

                if (entityType == nameof(Book))
                {
                    return this.RedirectToAction("Edit", "Book", new { id });
                }

                return this.RedirectToAction("Edit", "Author", new { id });
            }
            catch
            {
                this.TempData[ErrorMessage] = "There was problem with uploding the file!";
            }

            if (entityType == nameof(Book))
            {
                return this.RedirectToAction("Edit", "Book", new { id });
            }

            return this.RedirectToAction("Edit", "Author", new { id });
        }

        [HttpGet]
        public async Task<IActionResult> DownloadFile(string id, string entityType)
        {
            try
            {
                // Check if entityType is valid
                if (entityType != nameof(Book) && entityType != nameof(Edition))
                {
                    this.TempData[ErrorMessage] = "Invalid entity type.!";

                    return this.RedirectToAction("All", "Book", new { id });
                }

                FileStreamResult fileStreamResult = await this.fileService.DownloadFileAsync(id, entityType);
                return fileStreamResult;
            }
            catch
            {
                this.TempData[ErrorMessage] = "There was problem with downloading the file!";
            }

            return this.RedirectToAction("All", "Book", new { id });
        }

        [HttpGet]
        public async Task<IActionResult> GetTextFileContent(string id, string entityType)
        {
            try
            {
                string filePath = await this.fileService.GetFilePathAsync(id, entityType);

                string fileContent = await this.fileService.GetFileContentAsync(filePath);

                return this.Content(fileContent);
            }
            catch
            {
                this.TempData[ErrorMessage] = "There was problem with getting the text file!";
            }

            return this.RedirectToAction("All", "Book", new { id });
        }
    }
}

LibraryManagementSystem.Web/Views/Edition/Add.cshtml
@using static LibraryManagementSystem.Common.GeneralApplicationConstants;

@model EditionFormModel

@{
    ViewData["Title"] = "Add Edition to Book";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @* Styles and links for Datepicker *@
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <style>
        .datepicker-dropdown {
            border-radius: 0 !important;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }

            .datepicker-dropdown table {
                width: 100%;
            }

                .datepicker-dropdown table thead tr:first-child th {
                    background-color: #007bff;
                    color: #fff;
                    border: none;
                }

                .datepicker-dropdown table td, .datepicker-dropdown table th {
                    text-align: center;
                }

                    .datepicker-dropdown table td.day:hover {
                        background-color: #f2f2f2;
                    }

                    .datepicker-dropdown table td.active, .datepicker-dropdown table td.active:hover {
                        background-color: #007bff;
                        color: #fff;
                    }

        /* Background color */
        body {
            background-color: #fdf6e3
        }

        /* Navbar positioning */
        .navbar {
            background-color: #d4d1c9 !important;
        }
    </style>
    <title>@ViewData["Title"]</title>
</head>
<body>
    <div class="container">
        <h1 class="text-center">Add Edition</h1>
        <br />
        <div class="form-group col-md-10">
            <form method="post">
                <div class="mb-4">
                    <label asp-for="@Model.BookId" class="form-label-add-edit">Select Book</label>
                    <select asp-for="@Model.BookId" class="form-control" aria-required="true" data-val-required="Please select a book">
                        <option value="">-- Select book --</option>
                        @foreach (var book in Model.BooksDropDown)
                        {
                            <option value="@book.Id">
                                <strong>Title:</strong> @book.Title |
                                <strong>Author:</strong> @book.AuthorName |
                                <strong>Publisher:</strong> @book.Publisher |
                                <strong>Year:</strong> @(book.YearPublished?.Substring(0, Math.Min(4, book.YearPublished.Length)))
                            </option>
                        }
                    </select>
                    <span asp-validation-for="@Model.BookId" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="Version"></label>
                    <input asp-for="Version" class="form-control" placeholder="" />
                    <span asp-validation-for="Version" class="small text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="Publisher"></label>
                    <input asp-for="Publisher" class="form-control" placeholder="" />
                    <span asp-validation-for="Publisher" class="small text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="EditionYear">Year of Edition</label>
                    <input asp-for="EditionYear" class="form-control" id="editionYear" placeholder="dd.mm.yyyy" autocomplete="off" />
                    <span asp-validation-for="EditionYear" class="small text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary">Add Edition</button>
            </form>
        </div>
    </div>
</body>
</html>

@section Scripts
{
    <script>
        @* Script for Datepicker *@
            $(document).ready(function () {
                var dateFormat = 'dd.mm.yyyy';

                $('#editionYear').datepicker({
                    minViewMode: 2,
                    format: dateFormat,
                    autoclose: true,
                    todayHighlight: true
                });
            });
    </script>

    <partial name="_ValidationScriptsPartial" />
}

LibraryManagementSystem.Web/Views/Edition/Edit.cshtml
@using static LibraryManagementSystem.Common.GeneralApplicationConstants;

@model EditionFormModel

@{
    ViewData["Title"] = "Edit book edition";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    @* Styles and links for Datepicker *@
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/2.1.3/toastr.min.css" integrity="sha512-6S2HWzVFxruDlZxI3sXOZZ4/eJ8AcxkQH1+JjSe/ONCEqR9L4Ysq5JdT5ipqtzU7WHalNwzwBv+iE51gNHJNqQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <style>
        .datepicker-dropdown {
            border-radius: 0 !important;
            box-shadow: 0 0 10px rgba(0,0,0,0.1);
        }

            .datepicker-dropdown table {
                width: 100%;
            }

                .datepicker-dropdown table thead tr:first-child th {
                    background-color: #007bff;
                    color: #fff;
                    border: none;
                }

                .datepicker-dropdown table td, .datepicker-dropdown table th {
                    text-align: center;
                }

                    .datepicker-dropdown table td.day:hover {
                        background-color: #f2f2f2;
                    }

                    .datepicker-dropdown table td.active, .datepicker-dropdown table td.active:hover {
                        background-color: #007bff;
                        color: #fff;
                    }

        /* Background color */
        body {
            background-color: #fdf6e3
        }

        /* Navbar positioning */
        .navbar {
            background-color: #d4d1c9 !important;
        }
    </style>
    <title>@ViewData["Title"]</title>
</head>
<body>
    <div class="container">
        <div class="form-group col-md-10">
            <br />
            <h3>Upload Edition File</h3>
            <br />
            <form asp-action="UploadFile" asp-controller="File" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label for="file">Choose file:</label>
                    <input type="file" name="file" id="file" class="form-control-file" />
                    <br />
                    @if (!string.IsNullOrEmpty(Model.FilePath))
                    {
                        string[] fileNameParts = Model.FilePath.Split('_');
                        if (fileNameParts.Length > 1)
                        {
                            string displayedFileName = fileNameParts[fileNameParts.Length - 1];
                            <p><b>Uploaded file:</b> @displayedFileName</p>
                        }
                    }
                </div>
                <input type="hidden" name="id" value="@Model.Id" />
                <input type="hidden" name="entityType" value="Edition" />
                <button type="submit" class="btn btn-primary">Upload File</button>
            </form>
        </div>
        <br />

        <h1 class="text-center">Edit Book Edition</h1>
        <br />

        <div class="form-group col-md-10">
            <form method="post">
                <div class="mb-4">
                    <label asp-for="@Model.BookId" class="form-label-add-edit">Select Book</label>
                    <select asp-for="@Model.BookId" class="form-control" aria-required="true" data-val-required="Please select a book">
                        <option value="">-- Select book --</option>
                        @foreach (var book in Model.BooksDropDown)
                        {
                            <option value="@book.Id">
                                <strong>Title:</strong> @book.Title |
                                <strong>Author:</strong> @book.AuthorName |
                                <strong>Publisher:</strong> @book.Publisher |
                                <strong>Year:</strong> @book.YearPublished
                            </option>
                        }
                    </select>
                    <span asp-validation-for="@Model.BookId" class="text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="Version"></label>
                    <input asp-for="Version" class="form-control" placeholder="" />
                    <span asp-validation-for="Version" class="small text-danger"></span>
                </div>
                <div class="form-group mb-3">
                    <label asp-for="Publisher"></label>
                    <input asp-for="Publisher" class="form-control" placeholder="" />
                    <span asp-validation-for="Publisher" class="small text-danger"></span>
                </div>
                <div class="form-group mb-4">
                    <label asp-for="EditionYear">Year of Edition</label>
                    <input asp-for="EditionYear" class="form-control" id="editionYear" placeholder="dd.mm.yyyy" autocomplete="off" value="@Model.EditionYear.ToString(GlobalDateFormat)" />
                    <span asp-validation-for="EditionYear" class="small text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary">Edit Edition</button>
            <div style="height: 80px;"></div>
            </form>
        </div>
    </div>
</body>
</html>

@section Scripts
{
    <script>
        @* Script for Datepicker *@
            $(document).ready(function () {
                var dateFormat = 'dd.mm.yyyy';

                $('#editionYear').datepicker({
                    minViewMode: 2,
                    format: dateFormat,
                    autoclose: true,
                    todayHighlight: true
                });
            });
    </script>

    <partial name="_ValidationScriptsPartial" />
}